// Auto-generated by build.js - DO NOT EDIT MANUALLY
// Generated at: 2025-07-26T17:18:26.475Z

/**
 * Auto-generated operation file registry with static imports
 * This file is created by scanning the operations directory at build time
 */

import * as export_settings_operations from './operations/export-settings-operations.js';
import * as manage_alignment from './operations/manage-alignment.js';
import * as manage_annotations from './operations/manage-annotations.js';
import * as manage_auto_layout from './operations/manage-auto-layout.js';
import * as manage_boolean from './operations/manage-boolean.js';
import * as manage_components from './operations/manage-components.js';
import * as manage_constraints from './operations/manage-constraints.js';
import * as manage_dev_resources from './operations/manage-dev-resources.js';
import * as manage_effects from './operations/manage-effects.js';
import * as manage_exports from './operations/manage-exports.js';
import * as manage_fills from './operations/manage-fills.js';
import * as manage_fonts from './operations/manage-fonts.js';
import * as manage_hierarchy from './operations/manage-hierarchy.js';
import * as manage_instances from './operations/manage-instances.js';
import * as manage_measurements from './operations/manage-measurements.js';
import * as manage_nodes from './operations/manage-nodes.js';
import * as manage_pages from './operations/manage-pages.js';
import * as manage_selection from './operations/manage-selection.js';
import * as manage_strokes from './operations/manage-strokes.js';
import * as manage_styles from './operations/manage-styles.js';
import * as manage_text from './operations/manage-text.js';
import * as manage_variables from './operations/manage-variables.js';
import * as manage_vector from './operations/manage-vector.js';
import * as ping_test from './operations/ping-test.js';
import * as plugin_status_operation from './operations/plugin-status-operation.js';
import * as sync_fonts from './operations/sync-fonts.js';

export const OPERATION_FILES = [
  "_operation-template",
  "base-operation",
  "export-settings-operations",
  "manage-alignment",
  "manage-annotations",
  "manage-auto-layout",
  "manage-boolean",
  "manage-components",
  "manage-constraints",
  "manage-dev-resources",
  "manage-effects",
  "manage-exports",
  "manage-fills",
  "manage-fonts",
  "manage-hierarchy",
  "manage-instances",
  "manage-measurements",
  "manage-nodes",
  "manage-pages",
  "manage-selection",
  "manage-strokes",
  "manage-styles",
  "manage-text",
  "manage-variables",
  "manage-vector",
  "ping-test",
  "plugin-status-operation",
  "sync-fonts"
];

/**
 * Static operation modules map
 */
const OPERATION_MODULES: Record<string, any> = {
  'export-settings-operations': export_settings_operations,
  'manage-alignment': manage_alignment,
  'manage-annotations': manage_annotations,
  'manage-auto-layout': manage_auto_layout,
  'manage-boolean': manage_boolean,
  'manage-components': manage_components,
  'manage-constraints': manage_constraints,
  'manage-dev-resources': manage_dev_resources,
  'manage-effects': manage_effects,
  'manage-exports': manage_exports,
  'manage-fills': manage_fills,
  'manage-fonts': manage_fonts,
  'manage-hierarchy': manage_hierarchy,
  'manage-instances': manage_instances,
  'manage-measurements': manage_measurements,
  'manage-nodes': manage_nodes,
  'manage-pages': manage_pages,
  'manage-selection': manage_selection,
  'manage-strokes': manage_strokes,
  'manage-styles': manage_styles,
  'manage-text': manage_text,
  'manage-variables': manage_variables,
  'manage-vector': manage_vector,
  'ping-test': ping_test,
  'plugin-status-operation': plugin_status_operation,
  'sync-fonts': sync_fonts
};

/**
 * Get operation module (replaces dynamic import)
 * Returns the operation module synchronously
 */
export function importOperation(fileName: string): any {
  const module = OPERATION_MODULES[fileName];
  if (!module) {
    throw new Error(`Module not found: ${fileName}`);
  }
  return module;
}
